language: swift
osx_image: xcode11
xcode_project: DataStructures.xcodeproj
xcode_scheme: DataStructures-Package
before_install:
  - swift package generate-xcodeproj
  - uname -a
#before_script:
#  - set -e -o pipefail
script:
  - xcodebuild test -scheme DataStructures-Package -enableCodeCoverage YES -derivedDataPath Build/

after_success:
  # Calculate functions coverage and show it in log
  - PROJECT_TARGET_NAME=DataStructures.framework
  - XCODE_TEST_RESULT=$(ls -1 Build/Logs/Test/ | grep xcresult | tail -1)
  # - xcrun xccov view --report --files-for-target $PROJECT_TARGET_NAME  $XCODE_TEST_RESULT
  - xcrun xccov view --report --files-for-target DataStructures.framework Build/Logs/Test/*.xcresult
  # Calculate line coverage and upload it to codecov
  - bash <(curl -s https://codecov.io/bash) -J 'DataStructures$' -D Build/
