version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.0"

    steps:
      - checkout
      - run:
          name: Build and run tests
          command: swift test
          environment:
            MY_ENVIRONMENT_VAR: My value

      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs

workflows:
  version: 2
  build-test-lint:
    jobs:
      - build-and-test
